path1 = ['-I', [pwd,'/sfunctions']];
path2 = ['-I', [pwd, '/../bridge_c']];
path3 = ['-I', [pwd,'/../..']];
path4 = ['-I', [pwd,'/../../third_party']];
path5 = ['-I', [pwd,'/../../protoc_genfiles']];
mex('-v','-g',...
    path1, path2, path3, path4, path5, ...
    'sfunctions/AutoBoxBridgeControlDeserializedSFunction_MultipleFrame.c',...
    '../../protoc_genfiles/modules/autobox_bridge/proto/autobox_control.pb-c.c',...
    '../bridge_c/client/bridge_receiver_preprocessing.c',...
    "../bridge_c/client/bridge_receiver_autobox_control.c",...
    "../bridge_c/common/bridge_buffer.c",...
    "../bridge_c/common/bridge_header_item.c",...
    "../bridge_c/common/bridge_header.c",...
    "../bridge_c/common/bridge_proto_diserialized_buf.c",...
    '../../protoc_genfiles/modules/common/proto/header.pb-c.c',...
    '../../protoc_genfiles/modules/common/proto/error_code.pb-c.c',...
    '../../third_party/protobuf-c/protobuf-c.c')
