package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "imar_proto",
    deps = [
        ":imar_proto_lib",
    ],
)

proto_library(
    name = "imar_proto_lib",
    srcs = [
        "imar_conf.proto",
    ],
    deps = [
    ],
)
