py_library(
    name = "common_utils",
    srcs = ["common_utils.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "geometry_parser",
    srcs = ["geometry_parser.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "geometry_utils",
    srcs = ["geometry_utils.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "lane_parser",
    srcs = ["lane_parser.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "road_parser",
    srcs = ["road_parser.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "laneSection_parser",
    srcs = ["laneSection_parser.py"],
    visibility = ["//visibility:public"],
)

